[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = stlink
debug_tool = stlink

build_flags = 
    -D __STM32__
    -D PS2X_DEBUG
    -D PS2X_READ_DELAY=10
    -fpermissive
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D HAL_UART_MODULE_ENABLED
    -D ENABLE_HWSERIAL2



monitor_speed = 57600

lib_deps =
    # Local drivers will be placed in the lib/ folder
    adafruit/Adafruit NeoPixel@^1.15.5
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.2



